### ISSUE TITLE
Is there a way to tell the CLI which "user" triggered the deployment?

### ISSUE THREAD

**Issue by sindre-nistad** [equinor/radix-cli#10]
Hi,
When using the Radix CLI from Azure DevOps / Pipelines, is there a way to tell radix, that a particular `deploy`ment was made from the CI?

**Comment by keaaa** [comment]
Hi, 
We're not very active on following issues reported on other repos than the radix-platform. 

This is currently not available through the cli. It should however not be too difficult, as radix API used by the cli already has it. If want to do a PR, we'll be very happy :) Or else i'll add this as a nice "good-first-issue"

OpenAPI: https://api.dev.radix.equinor.com/swaggerui/#/application/triggerPipelineDeploy

Regards
Kjell Erik

**Comment by olemoi** [comment]
Hi,

This feature has now been added to the Radix CLI. When creating a deploy job an argument 'user' is avaliable which accept strings.

Regards,
Ole
