### ISSUE TITLE
Programmatic login and login status

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/radix-cli#20]
Wrapping `rx` in some script, for automating Radix deploylment workflow, works today, but for cleaner scripts/user experience is would be useful to have two simple `rx` commands related to:
- Am I currently logged in?
- Log in

As an example from another CLI tool, the GitHub CLI (which we use together with `rx` to automatically create repo, set Radix webhook etc.) related commands would be:
- https://cli.github.com/manual/gh_auth_status
- https://cli.github.com/manual/gh_auth_login

respectively.

**Comment by satr** [comment]
Implemented. Use:
`rx login` to login or re-login
`rx logout` to logout
