### ISSUE TITLE
Device Code Flow does not work with Managed Devices in Radix CLI

### ISSUE THREAD

**Issue by emirgens** [equinor/radix-cli#89]
Unfourtunantly the device code flow dosent work particularily well together with compliant device. To my knowledge it has to do with the way you authenticate and that the part that is polling the endpoint also has to complete the compliant device verification. If that part is not implemented, it will fail the compliance check.

**Comment by nilsgstrabo** [comment]
Fixed in release [v1.16.0](https://github.com/equinor/radix-cli/releases/tag/v1.16.0)
